---
name: Major Version Updater
# Whenever a new release is made, push a major version tag
on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  update-major-version-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.2.2

      - name: version
        id: version
        shell: bash
        run: |
          # shellcheck disable=all
          tag=${GITHUB_REF/refs\/tags\//};
          version=${tag#v} ;
          major=${version%%.*} ;
          { echo "tag=${tag}"; echo "version=${version}"; echo "major=${major}"; } >> "$GITHUB_OUTPUT"

      - name: force update major tag
        run: |
          git tag v${{ steps.version.outputs.major }}
          git push origin refs/tags/v${{ steps.version.outputs.major }} -f
